# Application Name
spring.application.name=atm-backend

# Datasource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/demo_db
spring.datasource.username=root
spring.datasource.password=J@navi.31

# Swagger API Documentation
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Stripe API Keys
stripe.api.key=sk_test_51QjZkxLGIr01zNNghxMuvqq1g9zf3hKKsjUd6mh9lj5BbL8YlpQGSUZkIbQNM3NpcP7jVHeH6XK7dOPkpGACSxwk007ycwnEqO
stripe.public.key=pk_test_51QjZkxLGIr01zNNgJHufI8gXuRIendKU4BcHQvrnu8LYYKhFeEv9Lgubd49ckmRgvSYBIU89W9bMgDvMU74y5gop00tHhiBZmn
stripe.secret.key=sk_test_51QjZkxLGIr01zNNghxMuvqq1g9zf3hKKsjUd6mh9lj5BbL8YlpQGSUZkIbQNM3NpcP7jVHeH6XK7dOPkpGACSxwk007ycwnEqO