spring.application.name=atm-backend

spring.datasource.url=jdbc:mysql://localhost:3306/demo_db
spring.datasource.username=root
spring.datasource.password=J@navi.31

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update