# Project identification
sonar.projectKey=spring-dev
sonar.projectName=Spring Project Dev
sonar.host.url=http://localhost:9000
sonar.login=squ_0df15acf2f17be64bc2542a41c4ffaf68b02fa95
#sonar-sqp_d0770555864b56b91cc8a782e4164ea827053524
#pom-squ_f39d5b93d322bf92268a5f24f8c391b2fbf56a59

# Source code configuration
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Optional: Exclude files from analysis
sonar.exclusions=**/generated/**, **/test/**

# Branch name (specific to your branch)
sonar.branch.name=Dev
