# Project identification
sonar.projectKey=spring-dev
sonar.projectName=Spring Project Dev
sonar.host.url=http://localhost:9000
sonar.login=sqp_d0770555864b56b91cc8a782e4164ea827053524

# Source code configuration
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Optional: Exclude files from analysis
sonar.exclusions=**/generated/**, **/test/**

# Branch name (specific to your branch)
sonar.branch.name=Dev
